config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :jobs do
    collection do
      get :grow
      get :study
      get :cognitive
      get :search
    end
    resources :resumes
  end

  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
      end
      resources :resumes
    end
  end

  namespace :account do
    resources :jobs
  end

  namespace :groups do
    resources :grow
    resources :study
    resources :cognitive
  end

  root 'welcome#index'
end

app/models/job.rb
class Job < ApplicationRecord

validates :title, presence: { message: "请填写职称" }
validates :description, presence: { message: "请填写职位描述" }
validates :wage_lower_bound, presence: { message: "请填写最低薪水" }
validates :wage_upper_bound, presence: { message: "请填写最高薪水" }
validates :wage_lower_bound, numericality: { less_than: :wage_upper_bound, message: "薪水下限不能高于薪水上限" }
validates :wage_upper_bound, numericality: { greater_than: 0, message: "最小薪水必须大于零" }


belongs_to :user
has_many :resumes, dependent: :destroy
has_many :collections, dependent: :destroy
has_many :members, through: :collections, source: :user




  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end

  scope :published, -> { where(is_hidden: false) }
  scope :recent, -> { order('created_at DESC') }
  scope :high, -> { order('wage_upper_bound DESC')}
  scope :low, -> { order('wage_lower_bound DESC')}

end

app/controllers/account/jobs_controller.rb
class Account::JobsController < ApplicationController
  before_action :authenticate_user!

  def index
      @jobs = current_user.applied_jobs.recent.paginate(:page => params[:page], :per_page => 6)
  end

  def show
    @job = Job.find(params[:id])
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin
  layout "admin"

  def index
    @jobs = current_user.jobs.recent.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to admin_jobs_path, alert: "Job deleted"
  end

  def publish
    @job = Job.find(params[:id])
    @job.publish!
    redirect_to :back
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!
    redirect_to :back
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_lower_bound, :wage_upper_bound, :contact_email, :is_hidden, :category, :company, :city)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :find_job_and_check_permission, only: [:edit, :update, :destroy, ]
  before_action :validate_search_key, only: [:search]

  def index
    @jobs = case params[:order]
            when 'by_upper_bound'
              Job.published.high.paginate(:page => params[:page], :per_page => 10)
            when 'by_lower_bound'
              Job.published.low.paginate(:page => params[:page], :per_page => 10)
            else
              Job.published.recent.paginate(:page => params[:page], :per_page => 10)
            end
  end

  def show
    @job = Job.find(params[:id])
    if @job.is_hidden
      flash[:warning] = "This Job already archieved"
      redirect_to jobs_path
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @job.update(job_params)
      redirect_to jobs_path, notice: "更新职位成功！"
    else
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to jobs_path, notice: "删除职位成功！"
  end

  def grow
    @jobs = case params[:order]
    when 'by_lower_bound'
      Job.published.where(:category => "成长").order('wage_lower_bound DESC').paginate(:page => params[:page], per_page => 10)
    when 'by_upper_bound'
      Job.published.where(:category => "成长").order('wage_upper_bound DESC').paginate(:page => params[:page], per_page => 10)
    else
      Job.published.where(:category => "成长").recent.paginate(:page => params[:page], :per_page => 10)
    end
  end

  def study
    @jobs = case params[:order]
    when 'by_lower_bound'
      Job.published.where(:category => "学习").order('wage_lower_bound DESC').paginate(:page => params[:page], per_page => 10)
    when 'by_upper_bound'
      Job.published.where(:category => "学习").order('wage_upper_bound DESC').paginate(:page => params[:page], per_page => 10)
    else
      Job.published.where(:category => "学习").recent.paginate(:page => params[:page], :per_page => 10)
    end
  end

  def cognitive
    @jobs = case params[:order]
    when 'by_lower_bound'
      Job.published.where(:category => "认知").order('wage_lower_bound DESC').paginate(:page => params[:page], per_page => 10)
    when 'by_upper_bound'
      Job.published.where(:category => "认知").order('wage_upper_bound DESC').paginate(:page => params[:page], per_page => 10)
    else
      Job.published.where(:category => "认知").recent.paginate(:page => params[:page], :per_page => 10)
    end
  end

  def search
    if @query_string.present?
      # 显示符合关键字的公开职位 #
      search_result = Job.ransack(@search_criteria).result(:distinct => true)
      @jobs = search_result.published.paginate(:page => params[:page], :per_page => 10 )
      # 随机推荐五个职位 #
    end
  end

  protected

  def validate_search_key
    # 去除特殊字符 #
    @query_string = params[:keyword].gsub(/\\|\'|\/|\?/, "") if params[:keyword].present?
    @search_criteria = search_criteria(@query_string)
  end

  def search_criteria(query_string)
    # 筛选多个栏位 #
    { :title_or_company_or_city_or_category_cont => query_string }
  end

  private


    def find_job_and_check_permission
      @job = Job.find(params[:id])

      if current_user != @job.user
        redirect_to root_path, alert: "你没有权限修改！"
      end
    end

  def job_params
    params.require(:job).permit(:title, :description, :wage_lower_bound, :wage_upper_bound, :contact_email, :is_hidden, :category, :company, :city)
  end

end

app/helpers/account/jobs_helper.rb
module Account::JobsHelper
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper

  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end

  def render_job_category(job)
    if job.category == '成长'
      "fa fa-laptop"
    elsif job.category == '学习'
      "fa fa-tasks"
    elsif job.category == '认知'
      "fa fa-photo"
    elsif job.category == '运营'
      "fa fa-line-chart"
    elsif job.category == '市场'
      "fa fa-pie-chart"
    elsif job.category == '销售'
      "fa fa-cny"
    elsif job.category == '职能'
      "fa fa-paste"
    else
      "fa fa-address-book-o"
    end
  end

  # 薪水区间 #
  def render_job_wage(job)
    "#{job.wage_lower_bound}  ~ #{job.wage_upper_bound} "
  end

  # 判断是否投递过简历icon #
  def render_job_resumes(job)
    if job.resumes.count > 0
      "fa fa-envelope-open-o"
    else
      "fa fa-envelope-o"
    end
  end

end

app/views/admin/jobs/_form.html.erb
<%= simple_form_for [:admin, @job] do |f| %>
<div class="form-group">
    <%= f.input :title, :label => "合作项目" %>
    <%= f.input :description, :label => "职位描述" %>
    <%= f.input :wage_lower_bound, :label => "薪资下限" %>
    <%= f.input :wage_upper_bound, :label => "薪资上限" %>
    <%= f.input :category, :label => "社群" %>
    <%= f.input :company, :label => "公司" %>
    <%= f.input :city, :label => "城市" %>
    <%= f.input :contact_email, :label => "联系Email" %>
    <%= f.input :is_hidden, :label => "隐藏" %>
</div>
<%= f.submit "提交", class: "btn btn-default", data: {disable_with: "Submiting..."} %>
<% end %>

app/views/admin/jobs/edit.html.erb
<div class="admin-edit-page">
  <div class="col-md-4 col-md-offset-4">
    <h1 class="text-center">Edit a Job</h1>
    <hr>
    <%= render "form" %>
  </div>
</div>

app/views/admin/jobs/index.html.erb
  <div class="col-md-11 col-md-offset-1 job-content">
    <div class="main-box">

    <div class="col-md-12 col-xs-12 job-box row"> <!--白色背景-->

<div class="pull-right">
  <%= link_to("新增项目", new_admin_job_path, :class => "btn btn-default") %>
</div>

<br></br>

<table class="table table-boldered table-striped custab" >

  <thead>
    <tr>
      <td>合作项目</td>
      <td>收到简历</td>
      <td>薪资</td>
      <td>创建时间</td>
      <td>管理</td>
    </tr>
  </thead>

  <% @jobs.each do |job| %>
  <tr>
    <td>
      <%= render_job_status(job) %>
      <%= link_to(job.title, admin_job_path(job)) %>
    </td>
    <td> <%= link_to(job.resumes.count, admin_job_resumes_path(job)) %> </td>
    <td>
      <span class="badge badge-info">
          <span class="fa fa-rmb"></span>
            <%= job.wage_lower_bound%>
            ～
            <%= job.wage_upper_bound%>
      </span>
    </td>
    <td><%= job.created_at.to_date %></td>
    <td>
      <%= link_to edit_admin_job_path(job), class: "btn btn-xs btn-info" do%>
      <i class="fa fa-pencil"></i><% end %>
      <%= link_to admin_job_path(job), method: :delete, class: "btn btn-xs btn-danger", data:{ confirm: "你确定删除吗？"} do%>
      <i class="fa fa-trash-o"></i><% end %>
      <% if job.is_hidden %>
      <%= link_to publish_admin_job_path(job), method: :post, class: "btn btn-xs btn-success" do %>
      <i class="fa fa-eye"></i><% end %>
      <% else %>
      <%= link_to hide_admin_job_path(job), method: :post, class: "btn btn-xs btn-warning" do %>
      <i class="fa fa-eye-slash"></i><% end %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>
<div class="text-center">
   <%= will_paginate @jobs %>
</div>

</div>
</div>
</div>

app/views/admin/jobs/new.html.erb
<div class="admin-new-page">
  <div class="col-md-4 col-md-offset-4">
    <h1 class="text-center">新增</h1>
    <hr>
    <%= render "form" %>
  </div>
</div>

app/views/admin/jobs/show.html.erb
<div class="col-md-12">
    <div class="1111">
        <%= link_to("编辑", edit_admin_job_path(@job), class: "btn btn-default pull-right") %>
    </div>

    <h2><%= @job.title %></h2>
    <p style="font-size:10px; margin-bottom:30px;">创建时间:<%= @job.created_at%></p>
    <p>合作项目描述：<%= simple_format(@job.description) %></p>
    <p>薪资上限：<%= @job.wage_upper_bound %></p>
    <p>薪资下限：<%= @job.wage_lower_bound %></p>
    <p>联系方式：<%= @job.contact_email %></p>
</div>