config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :jobs do
    collection do
      get :grow
      get :study
      get :cognitive
      get :search
    end
    resources :resumes
  end

  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
      end
      resources :resumes
    end
  end

  namespace :account do
    resources :jobs
  end

  namespace :groups do
    resources :grow
    resources :study
    resources :cognitive
  end

  root 'welcome#index'
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
   <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
     <button class="close" data-dismiss="alert">x</button>
     <%= value %>
   </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2017 Cooperation Home
    <br>Design by cinly

  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <span class="glyphicon glyphicon-home"></span> Cooperation Home
      </a>

        <%= form_tag search_jobs_path, :method => :get, class: "navbar-form navbar-right" do %>
            <div class="input-group search-box">
              <input type="text" class="form-control" name="keyword" placeholder="搜索职位、公司或地点" value="<%= params[:keyword] %>">
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit">
                   <i class="fa fa-search"></i>
                  </button>
               </div>
            </div>
        <% end %>
    
    </div>



    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
            <li><%= link_to('<span class="glyphicon glyphicon-home"></span> Go Home'.html_safe, jobs_path) %></li>
        <% if !current_user %>
            <li><%= link_to('<span class="glyphicon glyphicon-user"></span> Sign Up'.html_safe, new_user_registration_path) %></li>
            <li><%= link_to('<span class="glyphicon glyphicon-log-in"></span> Login'.html_safe, new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <% if current_user.admin? %>
                  <%= link_to("<span class='glyphicon glyphicon-user'></span> Admin Panel".html_safe, admin_jobs_path) %>
                <% end %>
              </li>
              <li>
                  <%= link_to("<span class='glyphicon glyphicon-user'></span> My Jobs".html_safe, account_jobs_path) %>
              </li>
              <li class="divider"></li>
              <li> <%= link_to("<span class='glyphicon glyphicon-log-out'></span> 退出".html_safe,destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog" role="document">
    <div class="loginmodal-container">
       <h2>Log in</h2>
       <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
         <div class="form-inputs">
           <%= f.input :email, required: false, autofocus: true %>
           <%= f.input :password, required: false %>
           <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
         </div>
         <div class="form-actions">
           <%= f.button :submit, "Log in" %>
         </div>
       <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="loginmodal-container">
      <h2>Sign up</h2>
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :email, required: true, autofocus: true %>
          <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          <%= f.input :password_confirmation, required: true %>
        </div>
        <div class="form-actions">
            <%= f.button :submit, "Sign up" %>
        </div>
      <% end %>
    </div>
  </div>
</div>